packages:
  - workflow
  - model
  - ui
  - test
  - software
  - block

catalog:
  "@milaboratories/graph-maker": 1.4.2
  "@milaboratories/ts-builder": 1.4.0
  "@milaboratories/ts-configs": 1.2.3
  "@platforma-sdk/workflow-tengo": 5.24.0
  "@platforma-sdk/block-tools": 2.9.2
  "@platforma-sdk/model": 1.77.0
  "@platforma-sdk/ui-vue": 1.77.0
  "@platforma-sdk/test": 1.77.1
  "@milaboratories/helpers": 1.14.2
  "@platforma-sdk/tengo-builder": 3.0.5
  "@platforma-sdk/package-builder": 3.12.0
  "@platforma-sdk/blocks-deps-updater": 2.2.0
  "@platforma-sdk/eslint-config": 1.2.0

  "@platforma-open/milaboratories.runenv-python-3": 1.8.2

  "vue": 3.5.24

  "turbo": 2.8.11
  "typescript": ~5.6.3
  "vitest": ^4.0.18
  "eslint": ^9.38.0

  "shx": 0.4.0
  "@changesets/cli": 2.29.8
